// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Choop = require("choop");
var Choop$MyDirectoryName = require("../src/Choop.bs.js");

var app = Choop();

app.use((function (state, emitter) {
        console.log(state[/* increment */0]);
        emitter.emit("stuff", 10);
        return /* () */0;
      }));

app.route("/", (function (_, _$1) {
        return Choop$MyDirectoryName.Html[/* main */39](/* :: */[
                    Curry._1(Choop$MyDirectoryName.Html[/* Attributes */118][/* _class */11], "main-content"),
                    /* [] */0
                  ], /* :: */[
                    Choop$MyDirectoryName.Html[/* div */32](/* :: */[
                          Curry._1(Choop$MyDirectoryName.Html[/* Attributes */118][/* _class */11], "section__a"),
                          /* [] */0
                        ], /* :: */[
                          Choop$MyDirectoryName.Html[/* encodedText */5]("aa"),
                          /* [] */0
                        ]),
                    /* :: */[
                      Choop$MyDirectoryName.Html[/* div */32](/* :: */[
                            Curry._1(Choop$MyDirectoryName.Html[/* Attributes */118][/* _class */11], "section__b"),
                            /* [] */0
                          ], /* [] */0),
                      /* [] */0
                    ]
                  ]);
      }));

app.mount("body");

exports.app = app;
/* app Not a pure module */
