// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Printf = require("bs-platform/lib/js/printf.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var H = require("choop/h");

var Emitter = /* module */[];

function h(param) {
  switch (param.tag | 0) {
    case 0 : 
        return H(param[0], param[1], $$Array.of_list(param[2]));
    case 1 : 
        return H(param[0], param[1], undefined);
    case 2 : 
    case 3 : 
        return H("", null, param[0]);
    
  }
}

function attr(key, value) {
  return /* tuple */[
          key,
          value
        ];
}

function flag(key) {
  return /* tuple */[
          key,
          true
        ];
}

function tag(nodeName, attributes, children) {
  return h(/* ParentNode */Block.__(0, [
                nodeName,
                Js_dict.fromList(attributes),
                children
              ]));
}

function voidTag(nodeName, attributes) {
  return h(/* VoidElement */Block.__(1, [
                nodeName,
                Js_dict.fromList(attributes)
              ]));
}

function encodedText(content) {
  return /* EncodedText */Block.__(2, [content]);
}

function rawText(content) {
  return /* RawText */Block.__(3, [content]);
}

function emptyText() {
  return /* RawText */Block.__(3, [""]);
}

function comment(content) {
  return /* RawText */Block.__(3, [Curry._1(Printf.sprintf(/* Format */[
                      /* String_literal */Block.__(11, [
                          "<!-- ",
                          /* String */Block.__(2, [
                              /* No_padding */0,
                              /* String_literal */Block.__(11, [
                                  " -->",
                                  /* End_of_format */0
                                ])
                            ])
                        ]),
                      "<!-- %s -->"
                    ]), content)]);
}

function html(param, param$1) {
  return tag("html", param, param$1);
}

function head(param, param$1) {
  return tag("head", param, param$1);
}

function link(attr) {
  return voidTag("link", attr);
}

function meta(attr) {
  return voidTag("meta", attr);
}

function style(param, param$1) {
  return tag("style", param, param$1);
}

function title(param, param$1) {
  return tag("title", param, param$1);
}

function blockquote(param, param$1) {
  return tag("blockquote", param, param$1);
}

function body(param, param$1) {
  return tag("body", param, param$1);
}

function address(param, param$1) {
  return tag("address", param, param$1);
}

function article(param, param$1) {
  return tag("article", param, param$1);
}

function aside(param, param$1) {
  return tag("aside", param, param$1);
}

function footer(param, param$1) {
  return tag("footer", param, param$1);
}

function hgroup(param, param$1) {
  return tag("hgroup", param, param$1);
}

function h1(param, param$1) {
  return tag("h1", param, param$1);
}

function h2(param, param$1) {
  return tag("h2", param, param$1);
}

function h3(param, param$1) {
  return tag("h3", param, param$1);
}

function h4(param, param$1) {
  return tag("h4", param, param$1);
}

function h5(param, param$1) {
  return tag("h5", param, param$1);
}

function h6(param, param$1) {
  return tag("h6", param, param$1);
}

function header(param, param$1) {
  return tag("header", param, param$1);
}

function nav(param, param$1) {
  return tag("nav", param, param$1);
}

function section(param, param$1) {
  return tag("section", param, param$1);
}

function dd(param, param$1) {
  return tag("dd", param, param$1);
}

function div(param, param$1) {
  return tag("div", param, param$1);
}

function dl(param, param$1) {
  return tag("dl", param, param$1);
}

function dt(param, param$1) {
  return tag("dt", param, param$1);
}

function figcaption(param, param$1) {
  return tag("figcaption", param, param$1);
}

function figure(param, param$1) {
  return tag("figure", param, param$1);
}

function hr(param) {
  return voidTag("hr", param);
}

function li(param, param$1) {
  return tag("li", param, param$1);
}

function main(param, param$1) {
  return tag("main", param, param$1);
}

function ol(param, param$1) {
  return tag("ol", param, param$1);
}

function p(param, param$1) {
  return tag("p", param, param$1);
}

function pre(param, param$1) {
  return tag("pre", param, param$1);
}

function ul(param, param$1) {
  return tag("ul", param, param$1);
}

function a(param, param$1) {
  return tag("a", param, param$1);
}

function abbr(param, param$1) {
  return tag("abbr", param, param$1);
}

function b(param, param$1) {
  return tag("b", param, param$1);
}

function bdi(param, param$1) {
  return tag("bdi", param, param$1);
}

function bdo(param, param$1) {
  return tag("bdo", param, param$1);
}

function br(param) {
  return voidTag("br", param);
}

function cite(param, param$1) {
  return tag("cite", param, param$1);
}

function code(param, param$1) {
  return tag("code", param, param$1);
}

function data(param, param$1) {
  return tag("data", param, param$1);
}

function dfn(param, param$1) {
  return tag("dfn", param, param$1);
}

function em(param, param$1) {
  return tag("em", param, param$1);
}

function i(param, param$1) {
  return tag("i", param, param$1);
}

function kbd(param, param$1) {
  return tag("kbd", param, param$1);
}

function mark(param, param$1) {
  return tag("mark", param, param$1);
}

function q(param, param$1) {
  return tag("q", param, param$1);
}

function rp(param, param$1) {
  return tag("rp", param, param$1);
}

function rt(param, param$1) {
  return tag("rt", param, param$1);
}

function rtc(param, param$1) {
  return tag("rtc", param, param$1);
}

function ruby(param, param$1) {
  return tag("ruby", param, param$1);
}

function s(param, param$1) {
  return tag("s", param, param$1);
}

function samp(param, param$1) {
  return tag("samp", param, param$1);
}

function small(param, param$1) {
  return tag("small", param, param$1);
}

function span(param, param$1) {
  return tag("span", param, param$1);
}

function strong(param, param$1) {
  return tag("strong", param, param$1);
}

function sub(param, param$1) {
  return tag("sub", param, param$1);
}

function sup(param, param$1) {
  return tag("sup", param, param$1);
}

function time(param, param$1) {
  return tag("time", param, param$1);
}

function u(param, param$1) {
  return tag("u", param, param$1);
}

function $$var(param, param$1) {
  return tag("var", param, param$1);
}

function wbr(param) {
  return voidTag("wbr", param);
}

function area(param) {
  return voidTag("area", param);
}

function audio(param, param$1) {
  return tag("audio", param, param$1);
}

function img(param) {
  return voidTag("img", param);
}

function map(param, param$1) {
  return tag("map", param, param$1);
}

function track(param) {
  return voidTag("track", param);
}

function video(param, param$1) {
  return tag("video", param, param$1);
}

function embed(param) {
  return voidTag("embed", param);
}

function object_(param, param$1) {
  return tag("object", param, param$1);
}

function param(param$1) {
  return voidTag("param", param$1);
}

function source(param) {
  return voidTag("source", param);
}

function canvas(param, param$1) {
  return tag("canvas", param, param$1);
}

function noscript(param, param$1) {
  return tag("noscript", param, param$1);
}

function script(param, param$1) {
  return tag("script", param, param$1);
}

function del(param, param$1) {
  return tag("del", param, param$1);
}

function ins(param, param$1) {
  return tag("ins", param, param$1);
}

function caption(param, param$1) {
  return tag("caption", param, param$1);
}

function col(param) {
  return voidTag("col", param);
}

function colgroup(param, param$1) {
  return tag("colgroup", param, param$1);
}

function table(param, param$1) {
  return tag("table", param, param$1);
}

function tbody(param, param$1) {
  return tag("tbody", param, param$1);
}

function td(param, param$1) {
  return tag("td", param, param$1);
}

function tfoot(param, param$1) {
  return tag("tfoot", param, param$1);
}

function th(param, param$1) {
  return tag("th", param, param$1);
}

function thead(param, param$1) {
  return tag("thead", param, param$1);
}

function tr(param, param$1) {
  return tag("tr", param, param$1);
}

function button(param, param$1) {
  return tag("button", param, param$1);
}

function datalist(param, param$1) {
  return tag("datalist", param, param$1);
}

function fieldset(param, param$1) {
  return tag("fieldset", param, param$1);
}

function form(param, param$1) {
  return tag("form", param, param$1);
}

function input(param) {
  return voidTag("input", param);
}

function label(param, param$1) {
  return tag("label", param, param$1);
}

function legend(param, param$1) {
  return tag("legend", param, param$1);
}

function meter(param, param$1) {
  return tag("meter", param, param$1);
}

function optgroup(param, param$1) {
  return tag("optgroup", param, param$1);
}

function option(param, param$1) {
  return tag("option", param, param$1);
}

function output(param, param$1) {
  return tag("output", param, param$1);
}

function progress(param, param$1) {
  return tag("progress", param, param$1);
}

function select(param, param$1) {
  return tag("select", param, param$1);
}

function textarea(param, param$1) {
  return tag("textarea", param, param$1);
}

function details(param, param$1) {
  return tag("details", param, param$1);
}

function dialog(param, param$1) {
  return tag("dialog", param, param$1);
}

function menu(param, param$1) {
  return tag("menu", param, param$1);
}

function menuitem(param) {
  return voidTag("menuitem", param);
}

function summary(param, param$1) {
  return tag("summary", param, param$1);
}

function _abbr(param) {
  return /* tuple */[
          "abbr",
          param
        ];
}

function _accept(param) {
  return /* tuple */[
          "accept",
          param
        ];
}

function _acceptCharset(param) {
  return /* tuple */[
          "accept-charset",
          param
        ];
}

function _accesskey(param) {
  return /* tuple */[
          "accesskey",
          param
        ];
}

function _action(param) {
  return /* tuple */[
          "action",
          param
        ];
}

function _alt(param) {
  return /* tuple */[
          "alt",
          param
        ];
}

function _autocomplete(param) {
  return /* tuple */[
          "autocomplete",
          param
        ];
}

function _border(param) {
  return /* tuple */[
          "border",
          param
        ];
}

function _challenge(param) {
  return /* tuple */[
          "challenge",
          param
        ];
}

function _charset(param) {
  return /* tuple */[
          "charset",
          param
        ];
}

function _cite(param) {
  return /* tuple */[
          "cite",
          param
        ];
}

function _class(param) {
  return /* tuple */[
          "class",
          param
        ];
}

function _cols(param) {
  return /* tuple */[
          "cols",
          param
        ];
}

function _colspan(param) {
  return /* tuple */[
          "colspan",
          param
        ];
}

function _content(param) {
  return /* tuple */[
          "content",
          param
        ];
}

function _contenteditable(param) {
  return /* tuple */[
          "contenteditable",
          param
        ];
}

function _coords(param) {
  return /* tuple */[
          "coords",
          param
        ];
}

function _crossorigin(param) {
  return /* tuple */[
          "crossorigin",
          param
        ];
}

function _data(param) {
  return /* tuple */[
          "data",
          param
        ];
}

function _datetime(param) {
  return /* tuple */[
          "datetime",
          param
        ];
}

function _dir(param) {
  return /* tuple */[
          "dir",
          param
        ];
}

function _dirname(param) {
  return /* tuple */[
          "dirname",
          param
        ];
}

function _download(param) {
  return /* tuple */[
          "download",
          param
        ];
}

function _enctype(param) {
  return /* tuple */[
          "enctype",
          param
        ];
}

function _for(param) {
  return /* tuple */[
          "for",
          param
        ];
}

function _form(param) {
  return /* tuple */[
          "form",
          param
        ];
}

function _formaction(param) {
  return /* tuple */[
          "formaction",
          param
        ];
}

function _formenctype(param) {
  return /* tuple */[
          "formenctype",
          param
        ];
}

function _formmethod(param) {
  return /* tuple */[
          "formmethod",
          param
        ];
}

function _formtarget(param) {
  return /* tuple */[
          "formtarget",
          param
        ];
}

function _headers(param) {
  return /* tuple */[
          "headers",
          param
        ];
}

function _height(param) {
  return /* tuple */[
          "height",
          param
        ];
}

function _high(param) {
  return /* tuple */[
          "high",
          param
        ];
}

function _href(param) {
  return /* tuple */[
          "href",
          param
        ];
}

function _hreflang(param) {
  return /* tuple */[
          "hreflang",
          param
        ];
}

function _httpEquiv(param) {
  return /* tuple */[
          "http-equiv",
          param
        ];
}

function _id(param) {
  return /* tuple */[
          "id",
          param
        ];
}

function _integrity(param) {
  return /* tuple */[
          "integrity",
          param
        ];
}

function _keytype(param) {
  return /* tuple */[
          "keytype",
          param
        ];
}

function _kind(param) {
  return /* tuple */[
          "kind",
          param
        ];
}

function _label(param) {
  return /* tuple */[
          "label",
          param
        ];
}

function _lang(param) {
  return /* tuple */[
          "lang",
          param
        ];
}

function _list(param) {
  return /* tuple */[
          "list",
          param
        ];
}

function _low(param) {
  return /* tuple */[
          "low",
          param
        ];
}

function _manifest(param) {
  return /* tuple */[
          "manifest",
          param
        ];
}

function _max(param) {
  return /* tuple */[
          "max",
          param
        ];
}

function _maxlength(param) {
  return /* tuple */[
          "maxlength",
          param
        ];
}

function _media(param) {
  return /* tuple */[
          "media",
          param
        ];
}

function _mediagroup(param) {
  return /* tuple */[
          "mediagroup",
          param
        ];
}

function _method(param) {
  return /* tuple */[
          "method",
          param
        ];
}

function _min(param) {
  return /* tuple */[
          "min",
          param
        ];
}

function _minlength(param) {
  return /* tuple */[
          "minlength",
          param
        ];
}

function _name(param) {
  return /* tuple */[
          "name",
          param
        ];
}

function _optimum(param) {
  return /* tuple */[
          "optimum",
          param
        ];
}

function _pattern(param) {
  return /* tuple */[
          "pattern",
          param
        ];
}

function _placeholder(param) {
  return /* tuple */[
          "placeholder",
          param
        ];
}

function _poster(param) {
  return /* tuple */[
          "poster",
          param
        ];
}

function _preload(param) {
  return /* tuple */[
          "preload",
          param
        ];
}

function _rel(param) {
  return /* tuple */[
          "rel",
          param
        ];
}

function _rows(param) {
  return /* tuple */[
          "rows",
          param
        ];
}

function _rowspan(param) {
  return /* tuple */[
          "rowspan",
          param
        ];
}

function _sandbox(param) {
  return /* tuple */[
          "sandbox",
          param
        ];
}

function _spellcheck(param) {
  return /* tuple */[
          "spellcheck",
          param
        ];
}

function _scope(param) {
  return /* tuple */[
          "scope",
          param
        ];
}

function _shape(param) {
  return /* tuple */[
          "shape",
          param
        ];
}

function _size(param) {
  return /* tuple */[
          "size",
          param
        ];
}

function _sizes(param) {
  return /* tuple */[
          "sizes",
          param
        ];
}

function _span(param) {
  return /* tuple */[
          "span",
          param
        ];
}

function _src(param) {
  return /* tuple */[
          "src",
          param
        ];
}

function _srcdoc(param) {
  return /* tuple */[
          "srcdoc",
          param
        ];
}

function _srclang(param) {
  return /* tuple */[
          "srclang",
          param
        ];
}

function _start(param) {
  return /* tuple */[
          "start",
          param
        ];
}

function _step(param) {
  return /* tuple */[
          "step",
          param
        ];
}

function _style(param) {
  return /* tuple */[
          "style",
          param
        ];
}

function _tabindex(param) {
  return /* tuple */[
          "tabindex",
          param
        ];
}

function _target(param) {
  return /* tuple */[
          "target",
          param
        ];
}

function _title(param) {
  return /* tuple */[
          "title",
          param
        ];
}

function _translate(param) {
  return /* tuple */[
          "translate",
          param
        ];
}

function _type(param) {
  return /* tuple */[
          "type",
          param
        ];
}

function _usemap(param) {
  return /* tuple */[
          "usemap",
          param
        ];
}

function _value(param) {
  return /* tuple */[
          "value",
          param
        ];
}

function _width(param) {
  return /* tuple */[
          "width",
          param
        ];
}

function _wrap(param) {
  return /* tuple */[
          "wrap",
          param
        ];
}

function _onclick(param) {
  return /* tuple */[
          "onclick",
          param
        ];
}

function _oncontextmenu(param) {
  return /* tuple */[
          "oncontextmenu",
          param
        ];
}

function _ondblclick(param) {
  return /* tuple */[
          "ondblclick",
          param
        ];
}

function _onmousedown(param) {
  return /* tuple */[
          "onmousedown",
          param
        ];
}

function _onmouseenter(param) {
  return /* tuple */[
          "onmouseenter",
          param
        ];
}

function _onmouseleave(param) {
  return /* tuple */[
          "onmouseleave",
          param
        ];
}

function _onmousemove(param) {
  return /* tuple */[
          "onmousemove",
          param
        ];
}

function _onmouseout(param) {
  return /* tuple */[
          "onmouseout",
          param
        ];
}

function _onmouseover(param) {
  return /* tuple */[
          "onmouseover",
          param
        ];
}

function _onmouseup(param) {
  return /* tuple */[
          "onmouseup",
          param
        ];
}

function _ontouchcancel(param) {
  return /* tuple */[
          "ontouchcancel",
          param
        ];
}

function _ontouchend(param) {
  return /* tuple */[
          "ontouchend",
          param
        ];
}

function _ontouchmove(param) {
  return /* tuple */[
          "ontouchmove",
          param
        ];
}

function _ontouchstart(param) {
  return /* tuple */[
          "ontouchstart",
          param
        ];
}

function _onkeydown(param) {
  return /* tuple */[
          "onkeydown",
          param
        ];
}

function _onkeypress(param) {
  return /* tuple */[
          "onkeypress",
          param
        ];
}

function _onkeyup(param) {
  return /* tuple */[
          "onkeyup",
          param
        ];
}

function _ondrag(param) {
  return /* tuple */[
          "ondrag",
          param
        ];
}

function _ondragend(param) {
  return /* tuple */[
          "ondragend",
          param
        ];
}

function _ondragenter(param) {
  return /* tuple */[
          "ondragenter",
          param
        ];
}

function _ondragleave(param) {
  return /* tuple */[
          "ondragleave",
          param
        ];
}

function _ondragover(param) {
  return /* tuple */[
          "ondragover",
          param
        ];
}

function _ondragstart(param) {
  return /* tuple */[
          "ondragstart",
          param
        ];
}

function _ondrop(param) {
  return /* tuple */[
          "ondrop",
          param
        ];
}

function _onblur(param) {
  return /* tuple */[
          "onblur",
          param
        ];
}

function _onfocus(param) {
  return /* tuple */[
          "onfocus",
          param
        ];
}

function _onfocusin(param) {
  return /* tuple */[
          "onfocusin",
          param
        ];
}

function _onfocusout(param) {
  return /* tuple */[
          "onfocusout",
          param
        ];
}

function _oninput(param) {
  return /* tuple */[
          "oninput",
          param
        ];
}

function _onwheel(param) {
  return /* tuple */[
          "onwheel",
          param
        ];
}

var _async = /* tuple */[
  "async",
  true
];

var _autofocus = /* tuple */[
  "autofocus",
  true
];

var _autoplay = /* tuple */[
  "autoplay",
  true
];

var _checked = /* tuple */[
  "checked",
  true
];

var _controls = /* tuple */[
  "controls",
  true
];

var _default = /* tuple */[
  "default",
  true
];

var _defer = /* tuple */[
  "defer",
  true
];

var _disabled = /* tuple */[
  "disabled",
  true
];

var _formnovalidate = /* tuple */[
  "formnovalidate",
  true
];

var _hidden = /* tuple */[
  "hidden",
  true
];

var _ismap = /* tuple */[
  "ismap",
  true
];

var _loop = /* tuple */[
  "loop",
  true
];

var _multiple = /* tuple */[
  "multiple",
  true
];

var _muted = /* tuple */[
  "muted",
  true
];

var _novalidate = /* tuple */[
  "novalidate",
  true
];

var _readonly = /* tuple */[
  "readonly",
  true
];

var _required = /* tuple */[
  "required",
  true
];

var _reversed = /* tuple */[
  "reversed",
  true
];

var _scoped = /* tuple */[
  "scoped",
  true
];

var _selected = /* tuple */[
  "selected",
  true
];

var _typemustmatch = /* tuple */[
  "typemustmatch",
  true
];

var Attributes = /* module */[
  /* _abbr */_abbr,
  /* _accept */_accept,
  /* _acceptCharset */_acceptCharset,
  /* _accesskey */_accesskey,
  /* _action */_action,
  /* _alt */_alt,
  /* _autocomplete */_autocomplete,
  /* _border */_border,
  /* _challenge */_challenge,
  /* _charset */_charset,
  /* _cite */_cite,
  /* _class */_class,
  /* _cols */_cols,
  /* _colspan */_colspan,
  /* _content */_content,
  /* _contenteditable */_contenteditable,
  /* _coords */_coords,
  /* _crossorigin */_crossorigin,
  /* _data */_data,
  /* _datetime */_datetime,
  /* _dir */_dir,
  /* _dirname */_dirname,
  /* _download */_download,
  /* _enctype */_enctype,
  /* _for */_for,
  /* _form */_form,
  /* _formaction */_formaction,
  /* _formenctype */_formenctype,
  /* _formmethod */_formmethod,
  /* _formtarget */_formtarget,
  /* _headers */_headers,
  /* _height */_height,
  /* _high */_high,
  /* _href */_href,
  /* _hreflang */_hreflang,
  /* _httpEquiv */_httpEquiv,
  /* _id */_id,
  /* _integrity */_integrity,
  /* _keytype */_keytype,
  /* _kind */_kind,
  /* _label */_label,
  /* _lang */_lang,
  /* _list */_list,
  /* _low */_low,
  /* _manifest */_manifest,
  /* _max */_max,
  /* _maxlength */_maxlength,
  /* _media */_media,
  /* _mediagroup */_mediagroup,
  /* _method */_method,
  /* _min */_min,
  /* _minlength */_minlength,
  /* _name */_name,
  /* _optimum */_optimum,
  /* _pattern */_pattern,
  /* _placeholder */_placeholder,
  /* _poster */_poster,
  /* _preload */_preload,
  /* _rel */_rel,
  /* _rows */_rows,
  /* _rowspan */_rowspan,
  /* _sandbox */_sandbox,
  /* _spellcheck */_spellcheck,
  /* _scope */_scope,
  /* _shape */_shape,
  /* _size */_size,
  /* _sizes */_sizes,
  /* _span */_span,
  /* _src */_src,
  /* _srcdoc */_srcdoc,
  /* _srclang */_srclang,
  /* _start */_start,
  /* _step */_step,
  /* _style */_style,
  /* _tabindex */_tabindex,
  /* _target */_target,
  /* _title */_title,
  /* _translate */_translate,
  /* _type */_type,
  /* _usemap */_usemap,
  /* _value */_value,
  /* _width */_width,
  /* _wrap */_wrap,
  /* _onclick */_onclick,
  /* _oncontextmenu */_oncontextmenu,
  /* _ondblclick */_ondblclick,
  /* _onmousedown */_onmousedown,
  /* _onmouseenter */_onmouseenter,
  /* _onmouseleave */_onmouseleave,
  /* _onmousemove */_onmousemove,
  /* _onmouseout */_onmouseout,
  /* _onmouseover */_onmouseover,
  /* _onmouseup */_onmouseup,
  /* _ontouchcancel */_ontouchcancel,
  /* _ontouchend */_ontouchend,
  /* _ontouchmove */_ontouchmove,
  /* _ontouchstart */_ontouchstart,
  /* _onkeydown */_onkeydown,
  /* _onkeypress */_onkeypress,
  /* _onkeyup */_onkeyup,
  /* _ondrag */_ondrag,
  /* _ondragend */_ondragend,
  /* _ondragenter */_ondragenter,
  /* _ondragleave */_ondragleave,
  /* _ondragover */_ondragover,
  /* _ondragstart */_ondragstart,
  /* _ondrop */_ondrop,
  /* _onblur */_onblur,
  /* _onfocus */_onfocus,
  /* _onfocusin */_onfocusin,
  /* _onfocusout */_onfocusout,
  /* _oninput */_oninput,
  /* _onwheel */_onwheel,
  /* _async */_async,
  /* _autofocus */_autofocus,
  /* _autoplay */_autoplay,
  /* _checked */_checked,
  /* _controls */_controls,
  /* _default */_default,
  /* _defer */_defer,
  /* _disabled */_disabled,
  /* _formnovalidate */_formnovalidate,
  /* _hidden */_hidden,
  /* _ismap */_ismap,
  /* _loop */_loop,
  /* _multiple */_multiple,
  /* _muted */_muted,
  /* _novalidate */_novalidate,
  /* _readonly */_readonly,
  /* _required */_required,
  /* _reversed */_reversed,
  /* _scoped */_scoped,
  /* _selected */_selected,
  /* _typemustmatch */_typemustmatch
];

var _roleAlert = /* tuple */[
  "role",
  "alert"
];

var _roleAlertDialog = /* tuple */[
  "role",
  "alertdialog"
];

var _roleApplication = /* tuple */[
  "role",
  "application"
];

var _roleArticle = /* tuple */[
  "role",
  "article"
];

var _roleBanner = /* tuple */[
  "role",
  "banner"
];

var _roleButton = /* tuple */[
  "role",
  "button"
];

var _roleCell = /* tuple */[
  "role",
  "cell"
];

var _roleCheckBox = /* tuple */[
  "role",
  "checkbox"
];

var _roleColumnHeader = /* tuple */[
  "role",
  "columnheader"
];

var _roleComboBox = /* tuple */[
  "role",
  "combobox"
];

var _roleComplementary = /* tuple */[
  "role",
  "complementary"
];

var _roleContentInfo = /* tuple */[
  "role",
  "contentinfo"
];

var _roleDefinition = /* tuple */[
  "role",
  "definition"
];

var _roleDialog = /* tuple */[
  "role",
  "dialog"
];

var _roleDirectory = /* tuple */[
  "role",
  "directory"
];

var _roleDocument = /* tuple */[
  "role",
  "document"
];

var _roleFeed = /* tuple */[
  "role",
  "feed"
];

var _roleFigure = /* tuple */[
  "role",
  "figure"
];

var _roleForm = /* tuple */[
  "role",
  "form"
];

var _roleGrid = /* tuple */[
  "role",
  "grid"
];

var _roleGridCell = /* tuple */[
  "role",
  "gridcell"
];

var _roleGroup = /* tuple */[
  "role",
  "group"
];

var _roleHeading = /* tuple */[
  "role",
  "heading"
];

var _roleImg = /* tuple */[
  "role",
  "img"
];

var _roleLink = /* tuple */[
  "role",
  "link"
];

var _roleList = /* tuple */[
  "role",
  "list"
];

var _roleListBox = /* tuple */[
  "role",
  "listbox"
];

var _roleListItem = /* tuple */[
  "role",
  "listitem"
];

var _roleLog = /* tuple */[
  "role",
  "log"
];

var _roleMain = /* tuple */[
  "role",
  "main"
];

var _roleMarquee = /* tuple */[
  "role",
  "marquee"
];

var _roleMath = /* tuple */[
  "role",
  "math"
];

var _roleMenuBar = /* tuple */[
  "role",
  "menubar"
];

var _roleMenuItem = /* tuple */[
  "role",
  "menuitem"
];

var _roleMenuItemCheckBox = /* tuple */[
  "role",
  "menuitemcheckbox"
];

var _roleMenuItemRadio = /* tuple */[
  "role",
  "menuitemradio"
];

var _roleNavigation = /* tuple */[
  "role",
  "navigation"
];

var _roleNone = /* tuple */[
  "role",
  "none"
];

var _roleNote = /* tuple */[
  "role",
  "note"
];

var _roleOption = /* tuple */[
  "role",
  "option"
];

var _rolePresentation = /* tuple */[
  "role",
  "presentation"
];

var _roleProgressBar = /* tuple */[
  "role",
  "progressbar"
];

var _roleRadio = /* tuple */[
  "role",
  "radio"
];

var _roleRadioGroup = /* tuple */[
  "role",
  "radiogroup"
];

var _roleRegion = /* tuple */[
  "role",
  "region"
];

var _roleRow = /* tuple */[
  "role",
  "row"
];

var _roleRowGroup = /* tuple */[
  "role",
  "rowgroup"
];

var _roleRowHeader = /* tuple */[
  "role",
  "rowheader"
];

var _roleScrollBar = /* tuple */[
  "role",
  "scrollbar"
];

var _roleSearch = /* tuple */[
  "role",
  "search"
];

var _roleSearchBox = /* tuple */[
  "role",
  "searchbox"
];

var _roleSeparator = /* tuple */[
  "role",
  "separator"
];

var _roleSlider = /* tuple */[
  "role",
  "slider"
];

var _roleSpinButton = /* tuple */[
  "role",
  "spinbutton"
];

var _roleStatus = /* tuple */[
  "role",
  "status"
];

var _roleSwitch = /* tuple */[
  "role",
  "switch"
];

var _roleTab = /* tuple */[
  "role",
  "tab"
];

var _roleTable = /* tuple */[
  "role",
  "table"
];

var _roleTabList = /* tuple */[
  "role",
  "tablist"
];

var _roleTabPanel = /* tuple */[
  "role",
  "tabpanel"
];

var _roleTerm = /* tuple */[
  "role",
  "term"
];

var _roleTextBox = /* tuple */[
  "role",
  "textbox"
];

var _roleTimer = /* tuple */[
  "role",
  "timer"
];

var _roleToolBar = /* tuple */[
  "role",
  "toolbar"
];

var _roleToolTip = /* tuple */[
  "role",
  "tooltip"
];

var _roleTree = /* tuple */[
  "role",
  "tree"
];

var _roleTreeGrid = /* tuple */[
  "role",
  "treegrid"
];

var _roleTreeItem = /* tuple */[
  "role",
  "treeitem"
];

function _ariaActiveDescendant(param) {
  return /* tuple */[
          "aria-activedescendant",
          param
        ];
}

function _ariaAtomic(param) {
  return /* tuple */[
          "aria-atomic",
          param
        ];
}

function _ariaAutocomplete(param) {
  return /* tuple */[
          "aria-autocomplete",
          param
        ];
}

function _ariaBusy(param) {
  return /* tuple */[
          "aria-busy",
          param
        ];
}

function _ariaChecked(param) {
  return /* tuple */[
          "aria-checked",
          param
        ];
}

function _ariaColCount(param) {
  return /* tuple */[
          "aria-colcount",
          param
        ];
}

function _ariaColIndex(param) {
  return /* tuple */[
          "aria-colindex",
          param
        ];
}

function _ariaColSpan(param) {
  return /* tuple */[
          "aria-colspan",
          param
        ];
}

function _ariaControls(param) {
  return /* tuple */[
          "aria-controls",
          param
        ];
}

function _ariaCurrent(param) {
  return /* tuple */[
          "aria-current",
          param
        ];
}

function _ariaDescribedBy(param) {
  return /* tuple */[
          "aria-describedby",
          param
        ];
}

function _ariaDetails(param) {
  return /* tuple */[
          "aria-details",
          param
        ];
}

function _ariaDisabled(param) {
  return /* tuple */[
          "aria-disabled",
          param
        ];
}

function _ariaDropEffect(param) {
  return /* tuple */[
          "aria-dropeffect",
          param
        ];
}

function _ariaErrorMessage(param) {
  return /* tuple */[
          "aria-errormessage",
          param
        ];
}

function _ariaExpanded(param) {
  return /* tuple */[
          "aria-expanded",
          param
        ];
}

function _ariaFlowTo(param) {
  return /* tuple */[
          "aria-flowto",
          param
        ];
}

function _ariaGrabbed(param) {
  return /* tuple */[
          "aria-grabbed",
          param
        ];
}

function _ariaHasPopup(param) {
  return /* tuple */[
          "aria-haspopup",
          param
        ];
}

function _ariaHidden(param) {
  return /* tuple */[
          "aria-hidden",
          param
        ];
}

function _ariaInvalid(param) {
  return /* tuple */[
          "aria-invalid",
          param
        ];
}

function _ariaKeyShortcuts(param) {
  return /* tuple */[
          "aria-keyshortcuts",
          param
        ];
}

function _ariaLabel(param) {
  return /* tuple */[
          "aria-label",
          param
        ];
}

function _ariaLabelledBy(param) {
  return /* tuple */[
          "aria-labeledby",
          param
        ];
}

function _ariaLevel(param) {
  return /* tuple */[
          "aria-level",
          param
        ];
}

function _ariaLive(param) {
  return /* tuple */[
          "aria-live",
          param
        ];
}

function _ariaModal(param) {
  return /* tuple */[
          "aria-modal",
          param
        ];
}

function _ariaMultiline(param) {
  return /* tuple */[
          "aria-multiline",
          param
        ];
}

function _ariaMultiSelectable(param) {
  return /* tuple */[
          "aria-multiselectable",
          param
        ];
}

function _ariaOrientation(param) {
  return /* tuple */[
          "aria-orientation",
          param
        ];
}

function _ariaOwns(param) {
  return /* tuple */[
          "aria-owns",
          param
        ];
}

function _ariaPlaceholder(param) {
  return /* tuple */[
          "aria-placeholder",
          param
        ];
}

function _ariaPosInset(param) {
  return /* tuple */[
          "aria-posinset",
          param
        ];
}

function _ariaPressed(param) {
  return /* tuple */[
          "aria-pressed",
          param
        ];
}

function _ariaReadOnly(param) {
  return /* tuple */[
          "aria-readonly",
          param
        ];
}

function _ariaRelevant(param) {
  return /* tuple */[
          "aria-relevant",
          param
        ];
}

function _ariaRequired(param) {
  return /* tuple */[
          "aria-required",
          param
        ];
}

function _ariaRoleDescription(param) {
  return /* tuple */[
          "aria-roledescription",
          param
        ];
}

function _ariaRowCount(param) {
  return /* tuple */[
          "aria-rowcount",
          param
        ];
}

function _ariaRowIndex(param) {
  return /* tuple */[
          "aria-rowindex",
          param
        ];
}

function _ariaRowSpan(param) {
  return /* tuple */[
          "aria-rowspan",
          param
        ];
}

function _ariaSelected(param) {
  return /* tuple */[
          "aria-selected",
          param
        ];
}

function _ariaSetSize(param) {
  return /* tuple */[
          "aria-setsize",
          param
        ];
}

function _ariaSort(param) {
  return /* tuple */[
          "aria-sort",
          param
        ];
}

function _ariaValueMax(param) {
  return /* tuple */[
          "aria-valuemax",
          param
        ];
}

function _ariaValueMin(param) {
  return /* tuple */[
          "aria-valuemin",
          param
        ];
}

function _ariaValueNow(param) {
  return /* tuple */[
          "aria-valuenow",
          param
        ];
}

function _ariaValueText(param) {
  return /* tuple */[
          "aria-valuetext",
          param
        ];
}

var Accessibility = /* module */[
  /* _roleAlert */_roleAlert,
  /* _roleAlertDialog */_roleAlertDialog,
  /* _roleApplication */_roleApplication,
  /* _roleArticle */_roleArticle,
  /* _roleBanner */_roleBanner,
  /* _roleButton */_roleButton,
  /* _roleCell */_roleCell,
  /* _roleCheckBox */_roleCheckBox,
  /* _roleColumnHeader */_roleColumnHeader,
  /* _roleComboBox */_roleComboBox,
  /* _roleComplementary */_roleComplementary,
  /* _roleContentInfo */_roleContentInfo,
  /* _roleDefinition */_roleDefinition,
  /* _roleDialog */_roleDialog,
  /* _roleDirectory */_roleDirectory,
  /* _roleDocument */_roleDocument,
  /* _roleFeed */_roleFeed,
  /* _roleFigure */_roleFigure,
  /* _roleForm */_roleForm,
  /* _roleGrid */_roleGrid,
  /* _roleGridCell */_roleGridCell,
  /* _roleGroup */_roleGroup,
  /* _roleHeading */_roleHeading,
  /* _roleImg */_roleImg,
  /* _roleLink */_roleLink,
  /* _roleList */_roleList,
  /* _roleListBox */_roleListBox,
  /* _roleListItem */_roleListItem,
  /* _roleLog */_roleLog,
  /* _roleMain */_roleMain,
  /* _roleMarquee */_roleMarquee,
  /* _roleMath */_roleMath,
  /* _roleMenuBar */_roleMenuBar,
  /* _roleMenuItem */_roleMenuItem,
  /* _roleMenuItemCheckBox */_roleMenuItemCheckBox,
  /* _roleMenuItemRadio */_roleMenuItemRadio,
  /* _roleNavigation */_roleNavigation,
  /* _roleNone */_roleNone,
  /* _roleNote */_roleNote,
  /* _roleOption */_roleOption,
  /* _rolePresentation */_rolePresentation,
  /* _roleProgressBar */_roleProgressBar,
  /* _roleRadio */_roleRadio,
  /* _roleRadioGroup */_roleRadioGroup,
  /* _roleRegion */_roleRegion,
  /* _roleRow */_roleRow,
  /* _roleRowGroup */_roleRowGroup,
  /* _roleRowHeader */_roleRowHeader,
  /* _roleScrollBar */_roleScrollBar,
  /* _roleSearch */_roleSearch,
  /* _roleSearchBox */_roleSearchBox,
  /* _roleSeparator */_roleSeparator,
  /* _roleSlider */_roleSlider,
  /* _roleSpinButton */_roleSpinButton,
  /* _roleStatus */_roleStatus,
  /* _roleSwitch */_roleSwitch,
  /* _roleTab */_roleTab,
  /* _roleTable */_roleTable,
  /* _roleTabList */_roleTabList,
  /* _roleTabPanel */_roleTabPanel,
  /* _roleTerm */_roleTerm,
  /* _roleTextBox */_roleTextBox,
  /* _roleTimer */_roleTimer,
  /* _roleToolBar */_roleToolBar,
  /* _roleToolTip */_roleToolTip,
  /* _roleTree */_roleTree,
  /* _roleTreeGrid */_roleTreeGrid,
  /* _roleTreeItem */_roleTreeItem,
  /* _ariaActiveDescendant */_ariaActiveDescendant,
  /* _ariaAtomic */_ariaAtomic,
  /* _ariaAutocomplete */_ariaAutocomplete,
  /* _ariaBusy */_ariaBusy,
  /* _ariaChecked */_ariaChecked,
  /* _ariaColCount */_ariaColCount,
  /* _ariaColIndex */_ariaColIndex,
  /* _ariaColSpan */_ariaColSpan,
  /* _ariaControls */_ariaControls,
  /* _ariaCurrent */_ariaCurrent,
  /* _ariaDescribedBy */_ariaDescribedBy,
  /* _ariaDetails */_ariaDetails,
  /* _ariaDisabled */_ariaDisabled,
  /* _ariaDropEffect */_ariaDropEffect,
  /* _ariaErrorMessage */_ariaErrorMessage,
  /* _ariaExpanded */_ariaExpanded,
  /* _ariaFlowTo */_ariaFlowTo,
  /* _ariaGrabbed */_ariaGrabbed,
  /* _ariaHasPopup */_ariaHasPopup,
  /* _ariaHidden */_ariaHidden,
  /* _ariaInvalid */_ariaInvalid,
  /* _ariaKeyShortcuts */_ariaKeyShortcuts,
  /* _ariaLabel */_ariaLabel,
  /* _ariaLabelledBy */_ariaLabelledBy,
  /* _ariaLevel */_ariaLevel,
  /* _ariaLive */_ariaLive,
  /* _ariaModal */_ariaModal,
  /* _ariaMultiline */_ariaMultiline,
  /* _ariaMultiSelectable */_ariaMultiSelectable,
  /* _ariaOrientation */_ariaOrientation,
  /* _ariaOwns */_ariaOwns,
  /* _ariaPlaceholder */_ariaPlaceholder,
  /* _ariaPosInset */_ariaPosInset,
  /* _ariaPressed */_ariaPressed,
  /* _ariaReadOnly */_ariaReadOnly,
  /* _ariaRelevant */_ariaRelevant,
  /* _ariaRequired */_ariaRequired,
  /* _ariaRoleDescription */_ariaRoleDescription,
  /* _ariaRowCount */_ariaRowCount,
  /* _ariaRowIndex */_ariaRowIndex,
  /* _ariaRowSpan */_ariaRowSpan,
  /* _ariaSelected */_ariaSelected,
  /* _ariaSetSize */_ariaSetSize,
  /* _ariaSort */_ariaSort,
  /* _ariaValueMax */_ariaValueMax,
  /* _ariaValueMin */_ariaValueMin,
  /* _ariaValueNow */_ariaValueNow,
  /* _ariaValueText */_ariaValueText
];

var Html = /* module */[
  /* h */h,
  /* attr */attr,
  /* flag */flag,
  /* tag */tag,
  /* voidTag */voidTag,
  /* encodedText */encodedText,
  /* rawText */rawText,
  /* emptyText */emptyText,
  /* comment */comment,
  /* html */html,
  /* head */head,
  /* link */link,
  /* meta */meta,
  /* style */style,
  /* title */title,
  /* blockquote */blockquote,
  /* body */body,
  /* address */address,
  /* article */article,
  /* aside */aside,
  /* footer */footer,
  /* hgroup */hgroup,
  /* h1 */h1,
  /* h2 */h2,
  /* h3 */h3,
  /* h4 */h4,
  /* h5 */h5,
  /* h6 */h6,
  /* header */header,
  /* nav */nav,
  /* section */section,
  /* dd */dd,
  /* div */div,
  /* dl */dl,
  /* dt */dt,
  /* figcaption */figcaption,
  /* figure */figure,
  /* hr */hr,
  /* li */li,
  /* main */main,
  /* ol */ol,
  /* p */p,
  /* pre */pre,
  /* ul */ul,
  /* a */a,
  /* abbr */abbr,
  /* b */b,
  /* bdi */bdi,
  /* bdo */bdo,
  /* br */br,
  /* cite */cite,
  /* code */code,
  /* data */data,
  /* dfn */dfn,
  /* em */em,
  /* i */i,
  /* kbd */kbd,
  /* mark */mark,
  /* q */q,
  /* rp */rp,
  /* rt */rt,
  /* rtc */rtc,
  /* ruby */ruby,
  /* s */s,
  /* samp */samp,
  /* small */small,
  /* span */span,
  /* strong */strong,
  /* sub */sub,
  /* sup */sup,
  /* time */time,
  /* u */u,
  /* var */$$var,
  /* wbr */wbr,
  /* area */area,
  /* audio */audio,
  /* img */img,
  /* map */map,
  /* track */track,
  /* video */video,
  /* embed */embed,
  /* object_ */object_,
  /* param */param,
  /* source */source,
  /* canvas */canvas,
  /* noscript */noscript,
  /* script */script,
  /* del */del,
  /* ins */ins,
  /* caption */caption,
  /* col */col,
  /* colgroup */colgroup,
  /* table */table,
  /* tbody */tbody,
  /* td */td,
  /* tfoot */tfoot,
  /* th */th,
  /* thead */thead,
  /* tr */tr,
  /* button */button,
  /* datalist */datalist,
  /* fieldset */fieldset,
  /* form */form,
  /* input */input,
  /* label */label,
  /* legend */legend,
  /* meter */meter,
  /* optgroup */optgroup,
  /* option */option,
  /* output */output,
  /* progress */progress,
  /* select */select,
  /* textarea */textarea,
  /* details */details,
  /* dialog */dialog,
  /* menu */menu,
  /* menuitem */menuitem,
  /* summary */summary,
  /* Attributes */Attributes,
  /* Accessibility */Accessibility
];

var App = /* module */[];

exports.Emitter = Emitter;
exports.Html = Html;
exports.App = App;
/* Js_dict Not a pure module */
